dateModified: 1635945810
email:
  fromEmail: $CONTACT_FORM_EMAIL
  fromName: $DEFAULT_SITE_NAME
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.sendgrid.net
    password: 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
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: apikey
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    1a4d6286-7e5a-47a7-a5c0-e5c3d03cd797: 'Employees Page' # Employees Page
    1d2fca35-7d0e-4f92-a63e-d4eb52da96fb: 'Common - Page Data' # Common - Page Data
    1fe98d66-28c3-46ac-917a-2c70a836a298: 'Customers Page' # Customers Page
    2b615e3e-47bc-4f90-b2be-0bc29d7bb5fb: 'Menu Item Text' # Menu Item Text
    2d5dabb5-f59e-42fe-9eea-6162feb07f12: 'Customers Slider' # Customers Slider
    2edfe7b7-d4f7-43af-9f36-348de5758a57: 'Box Title' # Box Title
    2f0e35a0-9f6b-4282-a620-2350b5030b30: 'Employees Page' # Employees Page
    2f84be3b-5a34-4262-9e3e-db7eb7724b31: 'Custom Link Label' # Custom Link Label
    2ffa2566-2460-463b-afca-80797ba55fcb: 'Header Image' # Header Image
    3a85c090-03fa-4b9c-ae60-4a6c49b7b318: 'Sidebar FAQ' # Sidebar FAQ
    3ca6ab4c-ebe2-4a33-b135-215bcdc9acb6: 'Type Link' # Type Link
    3f0d5825-c194-4574-b2c7-d84ac9bc4eea: 'Article Tags' # Article Tags
    3ffdb739-a429-4df1-be16-07f6252ad2e4: 'Contact Phone' # Contact Phone
    4dbfd059-90cc-4aa5-bb4b-f61f026fa9c9: 'Module ID' # Module ID
    4dfdb601-ad58-40b8-9c5d-f5e1012383e1: 'Header Help Box Title' # Header Help Box Title
    4efa5f34-e1d0-49d8-a290-fea288342d28: 'Description Title' # Description Title
    4f4b9f16-3719-4e97-88ae-67729adfd1ef: 'List Boxes' # List Boxes
    4fb673fb-d068-4a7f-bd74-bc88812a0b54: 'Services Page' # Services Page
    5b6d7881-9bc1-4b9e-8339-64da105704fb: 'Site Google Analytics GTM Code' # Site Google Analytics GTM Code
    05d883a7-5b0d-4af1-9083-a590140f56a0: 'Entry Link' # Entry Link
    5efe7a00-4dc8-42ef-afd2-c9da2657544f: 'Underline Title?' # Underline Title?
    6d567a3f-1db6-4a04-b03e-5651bd563854: 'Structure - Dira Customers' # Structure - Dira Customers
    6e7ba860-6c17-4f5d-9d5d-d0e0d006a58a: 'Hero Signature' # Hero Signature
    6e7cdd12-5e29-4b9e-9527-e21c05429c77: 'Is Page Link Disabled?' # Is Page Link Disabled?
    7a43c953-3dd4-40d5-bbe8-498e7411a32c: Content # Content
    7cbe98d3-3c01-4ebb-bb74-04967902d7d8: 'Hide Title?' # Hide Title?
    7ccd4d19-2082-47d1-9703-579319d1ce48: 'Entry Field' # Entry Field
    7cec95cc-1712-4f28-b46f-812763ed6230: 'Page URL' # Page URL
    7db5c248-29af-45a7-8d4f-a746e0a2717f: 'FAQ Answer' # FAQ Answer
    7dc5bbcf-ff73-47a5-9208-d52d6949453b: Search # Search
    7dd8487c-66de-4727-b79c-ff46e46ffcd3: 'Common - Simple Content' # Common - Simple Content
    7ed929cb-4184-4ca2-b087-3526c87aa38c: 'Contact Title' # Contact Title
    7f2bd309-8b75-4073-97f8-1ca769cc3598: 'Our Services Text' # Our Services Text
    8a4b5b11-31d8-46ca-a1aa-87aa567794f3: 'Entry Name' # Entry Name
    8b644d79-e5fd-49d0-be32-f18a505cd11c: 'Site Google Map Api Key' # Site Google Map Api Key
    8ba2db49-09ff-450a-9bee-c934b51cd39c: 'Articles Page' # Articles Page
    8c09a85d-b9e4-4e62-818c-9feff9987cfc: 'Entry Link' # Entry Link
    8c996efa-4ce4-4718-8b87-2cc4d9651b05: 'Driftsmeldinger List Boxes' # Driftsmeldinger List Boxes
    8ca9ce47-bfd4-4d95-bdae-4074e4ad3960: 'Entry Link' # Entry Link
    8d7659e1-81e9-4004-be63-a902999fb884: 'Person Phone' # Person Phone
    8daeab94-7bb8-466c-bf39-2c28af6ed290: 'Dira Contact' # Dira Contact
    8dec0694-79e6-43cf-9898-1f9633496ab5: Videos # Videos
    8fa4791a-dd0b-47e6-a011-d7e6215afa15: 'CTA Block With Info' # CTA Block With Info
    09ceb341-b5a9-4e3b-ac59-7e75640530e9: 'FAQ Question' # FAQ Question
    9e321a1e-9004-440c-8b87-683c4c686433: Default # Default
    11dfb393-6b7d-48eb-99f1-0be61d09d736: 'Custom Title' # Custom Title
    21be74b4-7c09-4912-9e0e-ab59ce248942: 'Entry Link' # Entry Link
    23f8b35b-e5f5-4fb4-8e50-2fb8d4722310: 'Site Footer' # Site Footer
    27aff492-2400-42d9-878a-bd134e93ebd6: $DEFAULT_SITE_NAME # $DEFAULT_SITE_NAME
    30d7b80d-5ede-47a8-8b53-9a193547c750: 'Page Description' # Page Description
    39ba0a6e-3f32-4b93-b823-0165cb29c021: 'Driftsmeldinger Data' # Driftsmeldinger Data
    43a7be5b-3720-4198-bf36-5503e241ba04: 'Boxes Title' # Boxes Title
    45eafd59-0c55-4b2e-9a35-b00733a1d9a6: 'Left Link URL' # Left Link URL
    045fc73f-b1cc-4e93-82c3-7ee4915d09f0: 'Underline Title?' # Underline Title?
    48b393c6-8937-4f82-9402-a1d6bd982171: 'Page Content' # Page Content
    49c1bd10-e7b1-4524-a499-ccdbd7e9744c: 'Remove Grey Line Under Title?' # Remove Grey Line Under Title?
    53fe6a6d-e33e-4463-9f20-fa4e7f997d67: 'Show Contact Info?' # Show Contact Info?
    55d65819-0bab-4e39-afc0-3c3822775728: 'Custom Label' # Custom Label
    55dc4b8d-b115-4dfa-8af3-fd56a6082361: 'Site Contact Data' # Site Contact Data
    61d008d2-57d9-4b99-a31c-cb4a13ecfeee: 'Menu Item URL' # Menu Item URL
    70b04be1-ca61-4f64-8983-47f37be11675: 'Page Title' # Page Title
    75f75307-13f3-4be8-9ea5-a4f0618befbe: 'Left Link Name' # Left Link Name
    79deb152-a2fa-41a3-8fa2-e08ac08c357e: 'Site Logo' # Site Logo
    080d7fef-a5d8-4d50-9714-9219b1c5538a: 'Dira Services' # Dira Services
    83ee1c31-8a76-4046-8635-204aee68afc5: 'Common - Page SEO' # Common - Page SEO
    87b4972b-92ef-409f-8aeb-c813bdf8acde: 'Text Block' # Text Block
    0108d81e-ba2f-4c2c-bacd-191ad45c7475: 'Module ID' # Module ID
    190bc3ff-c0d0-4640-a319-fc661baa93ff: 'List Boxes' # List Boxes
    260c39ff-27d8-4568-885f-ed49e60ce6f3: 'Placeholder for Message' # Placeholder for Message
    262f6609-b257-41a4-9d51-239c9ebf11a0: 'Custom URL' # Custom URL
    0327dc7a-7a0b-4462-bc2e-0331574e473d: 'Custom Contact Message' # Custom Contact Message
    328c167f-f82b-49e6-961e-b1fb63f10b0b: 'Bold?' # Bold?
    545cf97d-6435-49f6-aa1a-28fe63c5cdc4: 'Module Title' # Module Title
    554da952-3718-4c91-9a45-c39d32098057: 'Services Page' # Services Page
    572fdeee-777a-4336-98f5-46fc153cc014: 'Customers Page' # Customers Page
    629fb362-054b-4357-8f97-293195a9e8ad: 'Articles Tags' # Articles Tags
    666fa1ef-5a45-438a-b07a-373cb729a9f6: 'Open in New Tab?' # Open in New Tab?
    668d7ba4-39e2-4a10-80a8-51637517741b: 'Globals - Driftsmeldinger Data' # Globals - Driftsmeldinger Data
    686a6a58-bcd5-404d-a1aa-b7054a9c6531: 'Module ID' # Module ID
    724f0bd4-fbd2-43f0-a05b-d49b1e6458e9: 'Box Alert Color?' # Box Alert Color?
    797ee278-f08f-4929-bf15-e663d99f8bda: 'Box Title' # Box Title
    802d149e-940d-4c16-86d8-828db173b5cf: 'Operation Notices' # Operation Notices
    827b0b82-a3da-44b5-9f6e-cec83a636de2: 'Single - Employees' # Single - Employees
    2521f9df-22eb-469b-8ede-9fc16a2285f0: 'Intro Content & Sidebar' # Intro Content & Sidebar
    3267c69d-f206-4973-abaf-226e3e3b79b9: 'Structure - Dira Services' # Structure - Dira Services
    3426bbd8-ae24-4099-88d4-f6fe3f6b1e18: 'Use Custom Navigation?' # Use Custom Navigation?
    4300ee96-6132-4b62-a001-8a76366edd02: 'Module ID' # Module ID
    4368eab1-00a0-49d0-a574-5b60f62114c4: 'Header Title' # Header Title
    4832dfa7-3f48-4582-888b-f8351737ec61: 'Structure - Dira Articles' # Structure - Dira Articles
    5258e7de-fdc7-487f-9a45-2e567a7b1251: Images # Images
    5582c8a1-003f-4d0a-95cc-75e152b85d44: 'Header Image' # Header Image
    8466f386-7144-4ad9-b82b-ac3c75cab244: 'Initial Service' # Initial Service
    9988ff38-25e0-4b26-a127-b851d554aa33: Search # Search
    13528aa3-0b8b-4976-bb7d-69f81e7a6402: 'Person Title' # Person Title
    14299cac-2465-48a7-b136-f88a9b1af2cc: 'Show Driftsmeldinger Status Bar?' # Show Driftsmeldinger Status Bar?
    15215e08-90f2-4855-9648-6d888dc28949: 'Image in White' # Image in White
    16794c50-02a9-41b0-8542-c14899c2afe7: Default # Default
    022937fd-7366-4d89-88a2-60b81f98020c: 'Operation Notices' # Operation Notices
    26442f4f-35dc-488d-80da-e443cfc19968: 'Hide Title?' # Hide Title?
    40816dba-f57f-46d5-92bb-b0be3bd8ffc0: 'External URL' # External URL
    63603c32-943b-44d3-b9f3-62993f51ec89: 'Driftsmeldinger Data' # Driftsmeldinger Data
    84433a26-be49-4cba-b6e9-45a66eda95d3: 'Module ID' # Module ID
    86416bf7-8b17-4f84-a365-c3b2f72e8651: Default # Default
    89963b22-6f13-4ff3-98ca-a9b4938e95f3: 'Button Entry URL (Optional)' # Button Entry URL (Optional)
    96739bc9-60c8-4801-be54-b72498e7fd63: 'Hero Message' # Hero Message
    1305912f-e7bd-4297-b074-b9c45da795db: 'Module ID' # Module ID
    2202461d-285c-4b02-9aa1-66fea5228786: 'Site Custom Navigation' # Site Custom Navigation
    8114666e-7dcb-4bf9-a840-a1de2e760e23: 'Show Services Box?' # Show Services Box?
    16998436-1ecb-4524-980b-0d8f4541ffc1: 'Remove Grey Line Under Title?' # Remove Grey Line Under Title?
    46810640-b49a-4c9d-a2f6-753d2b789a89: 'Button Label (Optional)' # Button Label (Optional)
    62629706-5d42-4d72-8996-b97d67d6e0e6: Files # Files
    72312580-06a1-4859-97cb-64789885c224: Home # Home
    73929375-2a00-426e-afd8-1e3a9cb6c73f: 'Header Text' # Header Text
    78807107-21e9-4d51-ad56-2656d52fa405: 'Contact Form' # Contact Form
    a5d0b183-5bcc-4f50-85cf-4ef08fa68a86: 'Articles Slider' # Articles Slider
    a35b9601-4206-419f-a5fa-2bd0c1a50f0e: 'Featured Image' # Featured Image
    a72a30e0-25d7-4a6f-8cd5-65d459fa9f38: 'Service Icon' # Service Icon
    a77b8649-4933-4619-982a-ed27582197e6: 'Bold?' # Bold?
    a288d9a4-12b4-41c7-807b-7d1429b2a572: 'Custom Link Label' # Custom Link Label
    a856f8a8-6e0b-4f19-9da9-ee9ae49387dd: 'Article Excerpt' # Article Excerpt
    a67608a9-f9c9-4b46-8b52-1d1b08ddf5c8: 'Globals - Site Contact Data' # Globals - Site Contact Data
    aa4fee67-40c7-45d7-a28b-4017d0c8437f: 'Image in White Box' # Image in White Box
    ab7f2bee-57b1-4895-a2c2-67fa686a3bdc: 'Button URL (Optional)' # Button URL (Optional)
    acba53bd-9a9a-449d-b985-1145bfbad713: 'Show in Status Bar?' # Show in Status Bar?
    adf16dd3-4d01-4cab-9d30-c0b0653c0f9b: 'Module ID' # Module ID
    b0fd6549-02a5-4fcf-b6e5-cee1a7578a6e: 'Single - Customers' # Single - Customers
    b09757a1-537c-4ffb-9251-c9ae32e5e67b: 'Related Services' # Related Services
    b6c58e6c-68b6-429c-97e0-f82dddfb0ee8: 'Text in White Box' # Text in White Box
    b8f17bc2-6cfd-4ef6-94b2-1323df4f9f6a: 'Custom URL' # Custom URL
    b8fc7270-3447-477e-a9ea-f21be3c0cee3: 'Site Google UA Tracking Code' # Site Google UA Tracking Code
    b40adbd6-8340-4629-92c9-0a0ca1645886: 'Driftsmeldinger Data Title' # Driftsmeldinger Data Title
    b395b4bc-4cdd-4edf-a06c-5c3ed9e758cb: 'Page Image' # Page Image
    b428c6c7-61b0-430f-aaaf-76e0c36a018b: 'Page Content' # Page Content
    b632fdaf-39fd-4b72-96c2-7a2b926b3a21: 'Header - Page' # Header - Page
    b1646cdb-2688-4c38-ba18-70926d42fac7: 'Box Info' # Box Info
    b9738930-bf20-480c-a40c-9ce74ecb818f: 'Header Help Desk' # Header Help Desk
    ba02dee5-fb5b-452f-aa26-d867eb90408f: 'Module ID' # Module ID
    ba9a3316-329c-4df5-8ddd-9abc7ac9f7d7: 'Page Image Alt' # Page Image Alt
    bb3e1e90-15fa-4f81-8fc9-3f21a708c2af: 'Site Settings' # Site Settings
    bbbb83dc-f0d3-41a0-8337-9444a448f99d: 'Dira Services' # Dira Services
    bd49c2a5-121a-4c09-9252-a00bba91fc83: 'Globals - Site Footer' # Globals - Site Footer
    bdb763f6-73d0-4fe7-a326-df63c11f407a: 'Contact Email' # Contact Email
    bfce2596-da0c-4130-b8b5-30418ec20af6: 'Module ID' # Module ID
    c3f8c13e-959e-4337-9866-6db3e34456fc: 'Articles Page' # Articles Page
    c4e164b5-66b6-4259-9985-d28e3cceae21: 'Globals - Site Settings' # Globals - Site Settings
    c2013b67-3425-420d-ab87-b5421e5a2a48: Default # Default
    c3888ec4-a944-48bf-a9b2-47ba143013f1: 'Structure - Dira Employees' # Structure - Dira Employees
    c4624692-18bc-44a0-aec6-8a93e1dab109: 'Dira Articles' # Dira Articles
    ce7dcd0d-e834-4ddf-9787-b8b533ef54db: 'Custom Contact Title' # Custom Contact Title
    d5c3224c-f766-4625-ac73-882d233e1ff0: 'Is External URL?' # Is External URL?
    d7df0331-9b52-43af-9120-23a536377367: 'Box Info' # Box Info
    d40d4da7-62c5-4c97-bf28-d19a16cb7463: 'Module ID' # Module ID
    d60ec317-803c-46fa-b7c7-afb64e24faa1: 'Add Text Signature' # Add Text Signature
    d98b5e4a-c4c6-418e-a8c6-7833b12bc420: 'Common - Page Content' # Common - Page Content
    d7136f58-9984-4fc0-9d38-0f5fd8bad147: Home # Home
    d6682358-9591-4ce9-8f8b-88c36a490716: 'Dira Services - Detailed' # Dira Services - Detailed
    dab2ed87-f018-40d2-b65d-dc2233d0a211: 'Article Image' # Article Image
    dc4c72fc-fc7a-4701-ab4e-1a141165f786: 'Public Pages' # Public Pages
    dc6dc995-abcc-4436-82ce-807a1cbf67a0: 'Site Navigation' # Site Navigation
    dd03a0d7-4a40-4162-bef3-f490879fe99e: 'Globals - Site Navigation' # Globals - Site Navigation
    e4ff2116-04d7-4d28-b69c-7bf330bd31fd: 'Show Dira Services?' # Show Dira Services?
    e43e3cc9-599a-4be2-816e-e6a3c36dc896: 'Custom URL' # Custom URL
    ef3a50e2-faa0-4f00-9155-07b7768b0cba: 'Dira Employees' # Dira Employees
    f3c3c199-9112-4d05-8909-14670dd11c5f: 'Dira Customers' # Dira Customers
    f4815c5d-d14e-4071-bc18-3988c1941e58: $DEFAULT_SITE_NAME # $DEFAULT_SITE_NAME
    f50435e8-6ffd-4354-8b8a-305e2cbc61b2: 'Text in White' # Text in White
    fb84bf1a-5324-4c6b-998c-a9fc6d5d1134: 'Hide from Navigation?' # Hide from Navigation?
    fcedda28-c391-4b6d-80ab-e97a456ae1d2: Default # Default
    fd739832-07b5-48f8-b324-f892f7474a3d: 'Header - Home' # Header - Home
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'PÃ¥ vegne av'
      prependSubject: 'Ny melding fra Dira nettsted'
      successFlashMessage: 'Din melding har blitt sendt.'
      toEmail: $CONTACT_FORM_EMAIL
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $DEFAULT_SITE_NAME
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: Europe/Oslo
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
